# Generated by Django 4.2.1 on 2023-05-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_carte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carte',
            name='ordered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
