# Generated by Django 4.2.1 on 2023-05-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_carte_ordered_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carte',
            name='odered',
        ),
        migrations.RemoveField(
            model_name='carte',
            name='ordered_date',
        ),
        migrations.AddField(
            model_name='order',
            name='odered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
